export const APP_NAME = "UniShop";
export const APP_DESCRIPTION =
  "The student marketplace — connect with businesses and find everything you need for campus life.";

export const CATEGORIES = [
  { slug: "textbooks", name: "Textbooks & Supplies", icon: "BookOpen" },
  { slug: "electronics", name: "Electronics", icon: "Laptop" },
  { slug: "fashion", name: "Fashion", icon: "Shirt" },
  { slug: "services", name: "Services", icon: "Wrench" },
  { slug: "food", name: "Food & Drinks", icon: "Coffee" },
  { slug: "housing", name: "Housing", icon: "Home" },
  { slug: "other", name: "Other", icon: "Package" },
] as const;

export const ORDER_STATUSES: { value: string; label: string; color: string }[] =
  [
    { value: "placed", label: "Placed", color: "bg-blue-100 text-blue-700" },
    { value: "paid", label: "Paid", color: "bg-indigo-100 text-indigo-700" },
    {
      value: "shipped",
      label: "Shipped",
      color: "bg-amber-100 text-amber-700",
    },
    {
      value: "completed",
      label: "Completed",
      color: "bg-emerald-100 text-emerald-700",
    },
    {
      value: "cancelled",
      label: "Cancelled",
      color: "bg-rose-100 text-rose-700",
    },
  ];

export const PRODUCT_CONDITIONS: { value: string; label: string }[] = [
  { value: "new", label: "New" },
  { value: "like_new", label: "Like New" },
  { value: "good", label: "Good" },
  { value: "fair", label: "Fair" },
  { value: "used", label: "Used" },
];

/**
 * Ghanaian tertiary institutions a listing can be tied to (optional per
 * product). Served to a searchable picker, so length is fine.
 */
export const GHANAIAN_INSTITUTIONS: string[] = [
  // ── Public universities ──────────────────────────────────────────────
  "University of Ghana",
  "KNUST",
  "University of Cape Coast",
  "University of Education, Winneba",
  "University for Development Studies",
  "University of Energy and Natural Resources",
  "University of Health and Allied Sciences",
  "University of Mines and Technology",
  "University of Environment and Sustainable Development",
  "AAMUSTED",
  "Ghana Communication Technology University",
  "University of Media, Arts and Communication",
  "GIMPA",
  "UPSA",
  "Ghana School of Law",
  "Ghana Institute of Languages",
  // ── Public technical universities ────────────────────────────────────
  "Accra Technical University",
  "Kumasi Technical University",
  "Takoradi Technical University",
  "Ho Technical University",
  "Tamale Technical University",
  "Cape Coast Technical University",
  "Sunyani Technical University",
  "Koforidua Technical University",
  "Bolgatanga Technical University",
  "Wa Technical University",
  "University of Technology and Applied Sciences (UTAS)",
  // ── Colleges of education ─────────────────────────────────────────────
  "Accra College of Education",
  "Ada College of Education",
  "Agogo Presbyterian College of Education",
  "Akatsi College of Education",
  "Amedzofe College of Education",
  "Bagabaga College of Education",
  "Bia Lamplighter College of Education",
  "Bimbilla E.P. College of Education",
  "Bole College of Education",
  "Dambai College of Education",
  "Dormaa Presbyterian College of Education",
  "Enchi College of Education",
  "Foso College of Education",
  "Gambaga Girls College of Education",
  "Gbelle College of Education",
  "Jasikan College of Education",
  "Kibi Presbyterian College of Education",
  "Komenda College of Education",
  "Mampong Technical College of Education",
  "Mount Mary College of Education",
  "N.J. Ahmadiyya College of Education",
  "OLA College of Education",
  "Peki College of Education",
  "Presbyterian Women's College of Education",
  "Pwaluugu College of Education",
  "St. Ambrose College of Education",
  "St. Francis College of Education",
  "St. John's College of Education",
  "St. Joseph's College of Education",
  "St. Louis College of Education",
  "St. Monica's College of Education",
  "St. Teresa's College of Education",
  "St. Vincent College of Education",
  "SDA College of Education",
  "Tamale College of Education",
  "Tumu College of Education",
  "Tutugbenu College of Education",
  "Wesley College of Education",
  "Offinso College of Education",
  "Atebubu College of Education",
  "Kpando College of Education",
  "Gbewaa College of Education",
  "Berekum College of Education",
  "Nsawkaw College of Education",
  "Oti College of Education",
  "Hohoe College of Education",
  // ── Private universities & university colleges ────────────────────────
  "Ashesi University",
  "Central University",
  "Valley View University",
  "Academic City University",
  "Pentecost University",
  "Wisconsin International University College",
  "All Nations University",
  "Regent University College of Science and Technology",
  "Webster University Ghana",
  "Lancaster University Ghana",
  "Heritage Christian University",
  "Methodist University Ghana",
  "Catholic University of Ghana",
  "Presbyterian University, Ghana",
  "Christian Service University College",
  "Islamic University College, Ghana",
  "African University College of Communications",
  "Accra Institute of Technology",
  "Knutsford University College",
  "Data Link University College",
  "Maranatha University College",
  "Garden City University College",
  "Ghana Baptist University College",
  "Spiritan University College",
  "Family Health University College",
  "BlueCrest University College",
  "Zenith University College",
  "Radford University College",
  "Dominion University College",
  "Jayee University College",
  "University College of Management Studies",
  "KAAF University College",
  "Kings University College",
  "University of Applied Management",
  "Aseda University College",
  "Lakeside University College",
  "Saint Augustine University College",
  "Catholic Institute of Business and Technology",
  "Accra Business School",
  "University College of Agriculture and Environmental Studies",
  // ── Health & medical training institutions ────────────────────────────
  "Korle-Bu Nursing and Midwifery Training College",
  "Accra Nursing and Midwifery Training College",
  "Pantang Nursing and Midwifery Training College",
  "Tema Nursing and Midwifery Training College",
  "Kumasi Nursing and Midwifery Training College",
  "Effia-Nkwanta Nursing and Midwifery Training College",
  "Tamale Nursing and Midwifery Training College",
  "Bolgatanga Nursing and Midwifery Training College",
  "Ho Nursing and Midwifery Training College",
  "Cape Coast Nursing and Midwifery Training College",
  "Koforidua Nursing and Midwifery Training College",
  "Sunyani Nursing and Midwifery Training College",
  "Winneba Nursing and Midwifery Training College",
  "Nalerigu Nursing and Midwifery Training College",
  "Kintampo College of Health and Wellbeing",
  "Navrongo Midwifery Training College",
  "Yendi Nursing and Midwifery Training College",
  "Sefwi-Wiawso Nursing and Midwifery Training College",
  "Offinso Nursing and Midwifery Training College",
  "Agogo Nursing and Midwifery Training College",
  "Berekum Nursing and Midwifery Training College",
  "Mampong Nursing and Midwifery Training College",
  "Salaga Nursing and Midwifery Training College",
  "Damongo Nursing and Midwifery Training College",
  "Wa Nursing and Midwifery Training College",
  "Bibiani Nursing and Midwifery Training College",
  "Nkawkaw Nursing and Midwifery Training College",
  "Akim Oda Nursing and Midwifery Training College",
  "Kpando Midwifery Training College",
  "Ankaful Nursing and Midwifery Training College",
  "Bawku Nursing and Midwifery Training College",
  "Bechem Nursing and Midwifery Training College",
  "Bimbilla Nursing and Midwifery Training College",
  "Drobo Nursing and Midwifery Training College",
  "Gbugmayili Nursing and Midwifery Training College",
  "Jasikan Nursing and Midwifery Training College",
  "Kete-Krachi Nursing and Midwifery Training College",
  "Konongo-Odumase Nursing and Midwifery Training College",
  "Nadowli Nursing and Midwifery Training College",
  "Nkwanta Nursing and Midwifery Training College",
  "Tepa Nursing and Midwifery Training College",
  "Walewale Nursing and Midwifery Training College",
  "Jamasi Nursing and Midwifery Training College",
  "Asante-Mampong Nursing and Midwifery Training College",
  "Sekyere-South Nursing and Midwifery Training College",
  "Akim Tafo Nursing and Midwifery Training College",
  "Hohoe Nursing and Midwifery Training College",
  "Kukurantumi Nursing and Midwifery Training College",
  "Ghana College of Physicians and Surgeons",
  "Ghana College of Nurses and Midwives",
  "Ensign College of Public Health",
  "Narh-Bita College",
  // ── Theological & specialist institutes ───────────────────────────────
  "Trinity Theological Seminary",
  "Akrofi-Christaller Institute of Theology",
  "Good News Theological Seminary",
  "Ghana Baptist Theological Seminary",
  "Institute of Local Government Studies",
  "Ghana Armed Forces Command and Staff College",
  "Ghana Police Academy",
  "Institute of Chartered Accountants, Ghana",
];

export const ROUTES = {
  home: "/",
  shop: "/shop",
  product: (slug: string) => `/product/${slug}`,
  cart: "/cart",
  checkout: "/checkout",
  order: (id: string) => `/order/${id}`,
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  studentOrders: "/orders",
  studentInbox: "/inbox",
  studentWishlist: "/wishlist",
  inboxThread: (id: string) => `/inbox/${id}`,
  studentProfile: "/profile",
  businessOnboarding: "/business/onboarding",
  businessDashboard: "/business/dashboard",
  businessProducts: "/business/products",
  businessNewProduct: "/business/products/new",
  businessEditProduct: (id: string) => `/business/products/${id}/edit`,
  businessOrders: "/business/orders",
  businessInbox: "/business/inbox",
  businessInboxThread: (id: string) => `/business/inbox/${id}`,
  businessSettings: "/business/settings",
  adminDashboard: "/admin/dashboard",
  adminBusinesses: "/admin/businesses",
  adminUsers: "/admin/users",
  adminCategories: "/admin/categories",
  adminOrders: "/admin/orders",
  adminProducts: "/admin/products",
} as const;
